Repository CodersCommunity/forum.pasja-informatyki.local, pull requests merged in 2018-05, with the labels that each got.

#123 Dodanie obrazków do porad, nowych modyfikatorów w panelu administratora, arkuszu stylów i paru poprawek
  forum/qa-plugin/tips-widget/icons/brain.png
  forum/qa-plugin/tips-widget/icons/buttons.png
  forum/qa-plugin/tips-widget/icons/checkbox.png
  forum/qa-plugin/tips-widget/icons/code.png
  forum/qa-plugin/tips-widget/icons/comments.png
  forum/qa-plugin/tips-widget/icons/compose.png
  forum/qa-plugin/tips-widget/icons/faq.png
  forum/qa-plugin/tips-widget/icons/innovation.png
  forum/qa-plugin/tips-widget/icons/irc.png
  forum/qa-plugin/tips-widget/icons/preview.png
  forum/qa-plugin/tips-widget/icons/tags.png
  forum/qa-plugin/tips-widget/qa-plugin.php
  forum/qa-plugin/tips-widget/snippets/tips-page-content.html
  forum/qa-plugin/tips-widget/snippets/tips-widget-content.html
  forum/qa-plugin/tips-widget/styles/style.css
  forum/qa-plugin/tips-widget/tips-replace-phrases.php
  forum/qa-plugin/tips-widget/tips-widget-admin.php
  forum/qa-plugin/tips-widget/tips-widget-layer.php
  forum/qa-plugin/tips-widget/tips-widget-page.php
  forum/qa-plugin/tips-widget/tips-widget-widget.php
Labels: Feature, Need Review

#139 Administracja może wysyłać wiadomości prywatne do użytkowników którzy zablokowali taką opcję
  forum/qa-include/pages/message.php
  forum/qa-include/pages/user-profile.php
  forum/qa-theme/SnowFlat/qa-styles.css
Labels: Bug, Feature, Need Review

#146 Add target to link
  forum/qa-theme/SnowFlat/qa-theme.php
Labels: Bug
