Repository CodersCommunity/forum.pasja-informatyki.local, pull requests merged in 2018-02, with the labels that each got.

#116 Naprawa wielokrotnego wysyłania formularzy
  forum/qa-content/qa-forms-protection.js
  forum/qa-include/pages/ask.php
  forum/qa-include/pages/feedback.php
  forum/qa-include/pages/message.php
Labels: Critical, Need Review

#118 Dodanie tła dla bloczku kodu w trybie edycji
  forum/qa-plugin/ckeditor4/contents.css
Labels: Feature

#120 Remove Haxe from programming languages in CKEditor
  forum/qa-content/qa-page.js
  forum/qa-plugin/ckeditor4/plugins/syntaxhighlight/dialogs/syntaxhighlight.js
Labels: Bug

#124 Język polski w SyntaxHighlighterze
  forum/qa-plugin/ckeditor4/plugins/syntaxhighlight/lang/pl.js
  forum/qa-plugin/ckeditor4/plugins/syntaxhighlight/plugin.js
Labels: Need Review
