Repository CodersCommunity/forum.pasja-informatyki.local, pull requests merged in 2020-08, with the labels that each got.

#208 Optymalizacja przetwarzania bloczków z kodem
  dump/forum.sql
  forum/qa-content/qa-page.js
  forum/qa-content/qa-question.js
  forum/qa-include/qa-theme-base.php
  forum/qa-plugin/ckeditor4/plugins/syntaxhighlight/init.js
  forum/qa-plugin/q2apro-on-site-notifications/q2apro-onsitenotifications-layer.php
  forum/qa-theme/SnowFlat/qa-styles.css
Labels: Improvement

#215 Zmiana domeny API Discorda
  forum/qa-plugin/discord-integration/README.md
  forum/qa-plugin/discord-integration/src/discord-api.php
Labels: Improvement

#199 Raportowanie zgłoszeń z powodem - wersja poprawiona
  forum/qa-include/app/emails.php
  forum/qa-include/pages/question-post.php
  forum/qa-include/pages/question.php
  forum/qa-include/qa-theme-base.php
  forum/qa-plugin/report-reason/README.md
  forum/qa-plugin/report-reason/frontend/.babelrc
  forum/qa-plugin/report-reason/frontend/.gitignore
  forum/qa-plugin/report-reason/frontend/.prettierrc
  forum/qa-plugin/report-reason/frontend/dist/script.js
  forum/qa-plugin/report-reason/frontend/index.js
  forum/qa-plugin/report-reason/frontend/package-lock.json
  forum/qa-plugin/report-reason/frontend/package.json
  forum/qa-plugin/report-reason/frontend/src/ajaxService.js
  forum/qa-plugin/report-reason/frontend/src/bootstrap.js
  forum/qa-plugin/report-reason/frontend/src/flagController.js
  forum/qa-plugin/report-reason/frontend/src/formController.js
  forum/qa-plugin/report-reason/frontend/src/popupController.js
  forum/qa-plugin/report-reason/frontend/src/unFlagButton.js
  forum/qa-plugin/report-reason/frontend/style.css
  forum/qa-plugin/report-reason/frontend/test/prepareTestFiles.js
  forum/qa-plugin/report-reason/frontend/test/spec/ajaxService.spec.js
  forum/qa-plugin/report-reason/frontend/test/spec/bootstrap.spec.js
  forum/qa-plugin/report-reason/frontend/test/spec/flagController.spec.js
  forum/qa-plugin/report-reason/frontend/test/spec/popupController.spec.js
  forum/qa-plugin/report-reason/frontend/test/spec/unFlagButton.spec.js
  forum/qa-plugin/report-reason/frontend/webpack.config.js
  forum/qa-plugin/report-reason/metadata.json
  forum/qa-plugin/report-reason/q2apro-flag-reasons-admin.php
  forum/qa-plugin/report-reason/q2apro-flag-reasons-event.php
  forum/qa-plugin/report-reason/q2apro-flag-reasons-lang-default.php
  forum/qa-plugin/report-reason/q2apro-flag-reasons-layer.php
  forum/qa-plugin/report-reason/q2apro-flag-reasons-page.php
  forum/qa-plugin/report-reason/q2apro-flag-reasons-validation.php
  forum/qa-plugin/report-reason/qa-plugin.php
  forum/qa-plugin/user-changeable-theme/themes/dark/build/main.css
  forum/qa-plugin/user-changeable-theme/themes/dark/src/elements/sites/_question.scss
  forum/qa-theme/SnowFlat/qa-styles.css
Labels: Feature

#219 Poprawka błędów undefined index w pluginie powodów zgłoszeń
  forum/qa-plugin/report-reason/q2apro-flag-reasons-event.php
  forum/qa-plugin/report-reason/q2apro-flag-reasons-layer.php
Labels: Bug
