Repository CodersCommunity/forum.pasja-informatyki.local, pull requests merged in 2020-10, with the labels that each got.

#224 Przeładowanie strony po kliknięciu w nowe powiadomienie dotyczące obecnej strony
  forum/qa-plugin/q2apro-on-site-notifications/script.js
Labels: Bug

#223 Poprawka znaków spacji w kodzie kopiowanym przez przycisk
  forum/qa-plugin/ckeditor4/plugins/syntaxhighlight/init.js
Labels: Bug

#216 Omijanie cache przeglądarek - wersja plików
  dump/forum.sql
  forum/qa-config-example.php
  forum/qa-include/app/format.php
  forum/qa-include/pages/admin/admin-approve.php
  forum/qa-include/pages/admin/admin-categories.php
  forum/qa-include/pages/admin/admin-default.php
  forum/qa-include/pages/admin/admin-flagged.php
  forum/qa-include/pages/admin/admin-hidden.php
  forum/qa-include/pages/admin/admin-moderate.php
  forum/qa-include/pages/admin/admin-plugins.php
  forum/qa-include/pages/admin/admin-points.php
  forum/qa-include/pages/admin/admin-stats.php
  forum/qa-include/pages/ask.php
  forum/qa-include/pages/messages.php
  forum/qa-include/pages/question.php
  forum/qa-include/pages/user-profile.php
  forum/qa-include/pages/user-wall.php
  forum/qa-include/qa-base.php
  forum/qa-include/qa-page.php
  forum/qa-include/qa-theme-base.php
  forum/qa-plugin/async-notifications/async-notifications-layer.php
  forum/qa-plugin/ckeditor4/CkEditor.php
  forum/qa-plugin/ckeditor4/qa-ckeditor4-layer.php
  forum/qa-plugin/q2a-social-share-master/qa-social-share-layer.php
  forum/qa-plugin/q2apro-on-site-notifications/q2apro-onsitenotifications-layer.php
  forum/qa-plugin/report-reason/q2apro-flag-reasons-layer.php
  forum/qa-plugin/show-online-user-count/show-online-user-count-widget.php
  forum/qa-theme/SnowFlat/qa-theme.php
Labels: Improvement

#227 Poprawka dodawania oznakowania wersji zasobów - wykluczenie zewnętrznych
  forum/qa-include/qa-page.php
  forum/qa-include/qa-theme-base.php
Labels: Bug, Critical

#228 Ograniczenie wyświetlania linków na profilu
  forum/qa-include/app/format.php
  forum/qa-include/app/users.php
  forum/qa-include/pages/user-profile.php
Labels: Improvement

#230 Zmiana domyślnie wybranej podkategorii na brak wyboru
  forum/qa-content/qa-ask.js
  forum/qa-include/lang/qa-lang-question.php
  forum/qa-include/pages/ask.php
  forum/qa-lang/pl/qa-lang-options.php
  forum/qa-lang/pl/qa-lang-question.php
Labels: Improvement
