Repository CodersCommunity/forum.pasja-informatyki.local, pull requests merged in 2020-03, with the labels that each got.

#162 Aktualizacja Ubuntu w Vagrancie
  Vagrantfile
  ansible/playbook.yml
  ansible/roles/apache/tasks/main.yml
  ansible/roles/mysql/tasks/main.yml
  ansible/roles/php/tasks/main.yml
  ansible/roles/php/tasks/php_ini_configure.yml
  ansible/roles/server/tasks/main.yml
  ansible/roles/xdebug/tasks/main.yml
Labels: Bug

#166 Podbicie wersji php do 7.1
  .gitignore
  ansible/roles/php/handlers/main.yml
  ansible/roles/php/tasks/configure.yml
  ansible/roles/php/tasks/main.yml
  ansible/roles/php/tasks/mod-php.yml
  ansible/roles/php/tasks/pecl.yml
  ansible/roles/php/tasks/php-cli.yml
  ansible/roles/php/tasks/php-fpm.yml
  ansible/roles/php/tasks/php_ini_configure.yml
  forum/composer.json
  forum/composer.lock
  forum/index.php
  forum/qa-include/app/emails.php
  forum/qa-include/app/upload.php
  forum/qa-include/app/users.php
  forum/qa-include/db/post-create.php
  forum/qa-include/db/post-update.php
  forum/qa-include/db/votes.php
  forum/qa-include/qa-base.php
  forum/qa-include/qa-db.php
  forum/qa-include/util/image.php
  forum/qa-plugin/ckeditor4/metadata.json
  forum/qa-plugin/q2a-badges-master/metadata.json
  forum/qa-plugin/q2a-comment-voting-master/metadata.json
  forum/qa-plugin/q2a-embed-master/metadata.json
  forum/qa-plugin/q2a-featured-master/metadata.json
  forum/qa-plugin/q2a-open-login-master/metadata.json
  forum/qa-plugin/q2a-poll-master/metadata.json
  forum/qa-plugin/q2a-smilies-master/metadata.json
  forum/qa-plugin/q2a-user-activity-plus-master/metadata.json
  forum/qa-plugin/q2a-user-activity-plus-master/qa-user-activity.php
  forum/qa-plugin/q2am-hide-sidebar-master/metadata.json
  forum/qa-plugin/q2apro-most-active-users-master/metadata.json
  forum/qa-plugin/q2apro-on-site-notifications/metadata.json
  forum/qa-plugin/q2apro-warn-on-leave/metadata.json
  forum/qa-plugin/q2apro-warn-on-leave/q2apro-warnonleave-layer.php
  forum/qa-plugin/show-online-user-count/metadata.json
  forum/qa-plugin/tips-widget/metadata.json
Labels: Assigned, Ready to merge

#130 Naprawa stron 403
  forum/.htaccess
Labels: Bug, Critical, Ready to merge

#169 Konfiguracja w pliku ignorowanym przez Gita
  .gitignore
  README.md
  ansible/roles/app/tasks/main.yml
  forum/index.php
  forum/qa-config-example.php
  forum/qa-config.php
  forum/qa-include/qa-base.php
Labels: Feature, Ready to merge

#173 Dodanie dockera
  .gitignore
  README.md
  Vagrantfile
  ansible/files/authorized_keys
  ansible/inventories/dev
  ansible/playbook.yml
  ansible/roles/apache/handlers/main.yml
  ansible/roles/apache/tasks/main.yml
  ansible/roles/apache/templates/vhost22.conf.tpl
  ansible/roles/apache/templates/vhost24.conf.tpl
  ansible/roles/app/tasks/main.yml
  ansible/roles/composer/tasks/main.yml
  ansible/roles/mysql/tasks/main.yml
  ansible/roles/php/handlers/main.yml
  ansible/roles/php/tasks/configure.yml
  ansible/roles/php/tasks/main.yml
  ansible/roles/php/tasks/mod-php.yml
  ansible/roles/php/tasks/pecl.yml
  ansible/roles/php/tasks/php-cli.yml
  ansible/roles/php/tasks/php-fpm.yml
  ansible/roles/php/tasks/php_ini_configure.yml
  ansible/roles/php/templates/extension.tpl
  ansible/roles/server/tasks/main.yml
  ansible/roles/server/templates/timezone.tpl
  ansible/roles/vagrant_local/tasks/main.yml
  ansible/roles/xdebug/defaults/main.yml
  ansible/roles/xdebug/tasks/main.yml
  ansible/vars/all.yml
  ansible/windows.sh
  docker-compose.yml
  docker/www/Dockerfile
  docker/www/forum.conf
  docker/xdebug/.gitkeep
  dump/forum.sql
  forum/qa-config-example.php
  forum/qa-include/app/emails.php
Labels: Need Review
