Repository CodersCommunity/forum.pasja-informatyki.local, pull requests merged in 2021-07, with the labels that each got.

#270 Przeglądanie bloczka z kodem na pełnym ekranie
  forum/qa-plugin/ckeditor4/plugins/syntaxhighlight/init.js
  forum/qa-plugin/user-changeable-theme/themes/dark/build/main.css
  forum/qa-plugin/user-changeable-theme/themes/dark/package-lock.json
  forum/qa-plugin/user-changeable-theme/themes/dark/src/codeBlocks/_dark.scss
  forum/qa-theme/SnowFlat/qa-styles.css
Labels: Feature

#274 Bardziej elastyczna konfiguracja portu do WebSocketu
  forum/qa-config-example.php
  forum/qa-plugin/async-lists/async-lists-layer.php
  forum/qa-plugin/async-lists/js/async-questions-list.js
  web_socket.example.env
Labels: Improvement

#273 Normalizacja nietypowych tagów podczas zadawania pytania
  forum/qa-content/qa-ask.js
Labels: Bug

#272 Poprawka zbędnego pogrubiania treści pisanej w poście po automatycznej adnotacji
  forum/qa-content/qa-page.js
Labels: Bug

#267 Dodanie statusów http do niektórych odpowiedzi z błędami
  forum/qa-include/Q2A/Response.php
  forum/qa-include/app/admin.php
  forum/qa-include/pages/account.php
  forum/qa-include/pages/admin/admin-approve.php
  forum/qa-include/pages/admin/admin-flagged.php
  forum/qa-include/pages/admin/admin-hidden.php
  forum/qa-include/pages/admin/admin-moderate.php
  forum/qa-include/pages/ask.php
  forum/qa-include/pages/default.php
  forum/qa-include/pages/feedback.php
  forum/qa-include/pages/ip.php
  forum/qa-include/pages/message.php
  forum/qa-include/pages/messages.php
  forum/qa-include/pages/question.php
  forum/qa-include/pages/register.php
  forum/qa-include/pages/users-blocked.php
  forum/qa-include/pages/users-special.php
  forum/qa-include/qa-page-not-found.php
  forum/qa-include/qa-page.php
  forum/qa-plugin/q2a-change-username-limit/page/account.php
  forum/qa-plugin/q2a-user-activity-plus-master/qa-user-activity.php
Labels: Improvement
