Repository CodersCommunity/forum.pasja-informatyki.local, pull requests merged in 2021-04, with the labels that each got.

#244 Dodanie pluginu dla zmian nazwy użytkownika
  forum/qa-config-example.php
  forum/qa-plugin/q2a-change-username-limit/css/style.css
  forum/qa-plugin/q2a-change-username-limit/metadata.json
  forum/qa-plugin/q2a-change-username-limit/page/account.php
  forum/qa-plugin/q2a-change-username-limit/page/migrate.php
  forum/qa-plugin/q2a-change-username-limit/q2a-changeusernamelimit-admin.php
  forum/qa-plugin/q2a-change-username-limit/q2a-changeusernamelimit-event.php
  forum/qa-plugin/q2a-change-username-limit/q2a-changeusernamelimit-lang-default.php
  forum/qa-plugin/q2a-change-username-limit/q2a-changeusernamelimit-layer.php
  forum/qa-plugin/q2a-change-username-limit/q2a-changeusernamelimit-override.php
  forum/qa-plugin/q2a-change-username-limit/q2a-changeusernamelimit-widget.php
  forum/qa-plugin/q2a-change-username-limit/qa-plugin.php
Labels: Feature, Improvement

#248 Wysyłanie do serwera Node wybranych eventów
  forum/qa-plugin/async-lists/async-lists-event.php
Labels: Feature

#253 Zmiany w kategoriach
  forum/.htaccess
  forum/qa-content/javascript/imgpre.js
  forum/qa-theme/SnowFlat/icons/server0.png
  forum/qa-theme/SnowFlat/icons/server1.png
  forum/qa-theme/SnowFlat/qa-theme.php
Labels: Improvement

#257 Dodanie RWD dla listy historii zmian nicka
  forum/qa-plugin/q2a-change-username-limit/css/style.css
Labels: Bug
